# Copyright (c) 2020-2029 GUARD Project (https://www.guard-project.eu)
# author: Alex Carrega <alessandro.carrega@cnit.it>

port: 9999
debug: false
project: GUARD
title: SCMS
description: Service Chain Management System.
commands:
  list:
    scripta: ls
    daemon: false
  current-dir:
    script: pwd
    daemon: false
configurations:
  test-json:
    path: tests/test.json
    format: json
  test-yaml:
    path: tests/test.yaml
    format: yaml
parameters:
  enabled:
    source: tests/test.json
    format: json
    xpath:
      - agent
      - enabled
chains:
  ch1:
    uri: http://localhost:1111
    relationship: sibling
  ch2:
    uri: http://localhost:2222
    relationship: child
