# Copyright (c) 2022-2029 TNT-Lab (https://github.com/s2n-cnit/scms)
# author: Alex Carrega <alessandro.carrega@unige.it>

ch1:
  uri: http://localhost:1111
  relationship: sibling
ch3:
  uri: http://localhost:2222
  relationship: child
