# Copyright (c) 2022-2029 S2N National Lab @ CNIT (https://github.com/s2n-cnit/scms)
# author: Alex Carrega <alessandro.carrega@unige.it>

ch1:
  uri: http://localhost:1111
  relationship: sibling
ch3:
  uri: http://localhost:2222
  relationship: child
