# Copyright (c) 2022-2029 TNT-Lab (https://github.com/tnt-lab-unige-cnit/scms)
# author: Alex Carrega <alessandro.carrega@unige.it>

list:
  scripta: ls
  daemon: false
current-dir:
  script: pwd
  daemon: false
