# Copyright (c) 2022-2029 TNT-Lab (https://github.com/s2n-cnit/scms)
# author: Alex Carrega <alessandro.carrega@unige.it>

list:
  script: ls
  daemon: false
current-dir:
  script: pwd
  daemon: false
