# Copyright (c) 2022-2029 TNT-Lab (https://github.com/tnt-lab-unige-cnit/scms)
# author: Alex Carrega <alessandro.carrega@unige.it>

test-json:
  path: tests/test.json
  format: json
test-yaml:
  path: tests/test.yaml
  format: yaml
