# Copyright (c) 2022-2029 S2N National Lab @ CNIT (https://github.com/s2n-cnit/scms)
# author: Alex Carrega <alessandro.carrega@unige.it>

test-json:
  path: tests/test.json
  format: json
test-yaml:
  path: tests/test.yaml
  format: yaml
