version: 1
disable_existing_loggers: false

formatters:
    standard:
        format: "%(asctime)s [%(levelname)s] %(message)s"
        datefmt: "%Y-%m-%d %H:%M"

handlers:
    console:
        class: logging.StreamHandler
        formatter: standard
        stream: ext://sys.stdout

loggers:
    uvicorn:
        level: INFO
    uvicorn.error:
        level: ERROR
    uvicorn.access:
        level: INFO
        propagate: false

root:
    level: INFO
    handlers: [console]
    propagate: no
