# Copyright (c) 2022-2029 S2N National Lab @ CNIT (https://github.com/s2n-cnit/scms)
# author: Alex Carrega <alessandro.carrega@unige.it>

enabled:
  source: tests/test.json
  format: json
  xpath:
    - agent
    - enabled
periods:
  source: tests/test.yaml
  format: yaml
  xpath:
    - agents
    - period
