# Copyright (c) 2022-2029 TNT-Lab (https://github.com/s2n-cnit/scms)
# author: Alex Carrega <alessandro.carrega@unige.it>

host: 0.0.0.0
port: 9999
debug: true
log-level: info
workers: 5
reload: true
