# Copyright (c) 2022-2029 TNT-Lab (https://github.com/tnt-lab-unige-cnit/scms)
# author: Alex Carrega <alessandro.carrega@unige.it>

host: $SCMS_HOST
port: $SCMS_PORT
debug: $SCMS_DEBUG
log-level: $SCMS_LOG_LEVEL
workers: $SCMS_WORKERS
reload: $SCMS_RELOAD
